name: OmniNetwork
main: net.omniblock.network.OmniNetwork
depend: [OmniPackets]
load: STARTUP
author: Omniblock Developers Team
version: 2.5.7
description: Plugin core de OmniBlock
website: www.omniblock.net
commands:
   screen:
      description: Comando para las screens de Anuncios.
   omninetwork:
      aliases: [omninetwork, omnin, on]
      description: Comando principal de OmniNetwork.
   ban:
      aliases: [ban, banear]
      description: Comando de administración de Baneos de OmniNetwork.
   kick:
      aliases: [kick, kickear]
      description: Comando de administración de Kickeos de OmniNetwork.
   testsoccer:
      description: Comando de testeos de soccer.
   banco:
      aliases: [banco, bank, dinero]
      description: Maneja todos los comandos del tipo Banco/Dinero de OmniNetwork.
   rango:
      aliases: [rango, rank]
      description: Comando de administración de Rangos de OmniNetwork.